/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionAdd_Camera;
    QAction *actionRemove_Camera;
    QAction *actionExport;
    QAction *actionSettings;
    QAction *actionAdvanced_Search;
    QAction *actionRTSS;
    QAction *actionRTVS;
    QAction *actionSuper_Resolution;
    QAction *actionFootage_analysis;
    QAction *actionStatistics;
    QAction *actionVideo_log;
    QAction *actionInstance_log;
    QAction *actionDynamic;
    QAction *actionFixed;
    QAction *actionShow_Faces;
    QAction *actionAdd_face;
    QAction *actionTracking;
    QAction *actionAbout_2;
    QAction *actionDatabase_Configuration;
    QAction *actionSearch_by_date_and_time;
    QAction *actionStudent_Attendece;
    QAction *actionEmployee_Attendence;
    QAction *actionTotal_Present_Time_For_Each_Employe;
    QAction *actionSearch_By_Given_Image;
    QAction *actionFace_Notification;
    QAction *actionMedia_Player;
    QWidget *centralWidget;
    QVBoxLayout *verticalLayout;
    QHBoxLayout *horMenu;
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QWidget *seachLayoutWidget;
    QHBoxLayout *horizontalLayout;
    QSpacerItem *horizontalSpacer;
    QPushButton *startButton;
    QSpacerItem *horizontalSpacer_3;
    QLabel *iconWC;
    QSpacerItem *horizontalSpacer_4;
    QPushButton *tileButton;
    QSpacerItem *horizontalSpacer_6;
    QLineEdit *faceLineEdit;
    QPushButton *searchFaceButton;
    QSpacerItem *horizontalSpacer_8;
    QSpacerItem *horizontalSpacer_5;
    QLineEdit *LPRlineEdit;
    QPushButton *searchLPRbutton;
    QSpacerItem *horizontalSpacer_7;
    QComboBox *colorCombo;
    QComboBox *objectCombo;
    QPushButton *searchObjectButton;
    QSpacerItem *horizontalSpacer_10;
    QPushButton *pushButton;
    QSpacerItem *horizontalSpacer_11;
    QSpacerItem *horizontalSpacer_9;
    QSpacerItem *horizontalSpacer_2;
    QGridLayout *feedLayout;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuTools;
    QMenu *menuAnalyze;
    QMenu *menuLog;
    QMenu *menuView;
    QMenu *menuHelp;
    QMenu *menuDatabase;
    QMenu *menuNotification;
    QMenu *menuPlayback;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1376, 720);
        actionAdd_Camera = new QAction(MainWindow);
        actionAdd_Camera->setObjectName(QStringLiteral("actionAdd_Camera"));
        actionRemove_Camera = new QAction(MainWindow);
        actionRemove_Camera->setObjectName(QStringLiteral("actionRemove_Camera"));
        actionExport = new QAction(MainWindow);
        actionExport->setObjectName(QStringLiteral("actionExport"));
        actionSettings = new QAction(MainWindow);
        actionSettings->setObjectName(QStringLiteral("actionSettings"));
        actionAdvanced_Search = new QAction(MainWindow);
        actionAdvanced_Search->setObjectName(QStringLiteral("actionAdvanced_Search"));
        actionRTSS = new QAction(MainWindow);
        actionRTSS->setObjectName(QStringLiteral("actionRTSS"));
        actionRTVS = new QAction(MainWindow);
        actionRTVS->setObjectName(QStringLiteral("actionRTVS"));
        actionSuper_Resolution = new QAction(MainWindow);
        actionSuper_Resolution->setObjectName(QStringLiteral("actionSuper_Resolution"));
        actionFootage_analysis = new QAction(MainWindow);
        actionFootage_analysis->setObjectName(QStringLiteral("actionFootage_analysis"));
        actionStatistics = new QAction(MainWindow);
        actionStatistics->setObjectName(QStringLiteral("actionStatistics"));
        actionVideo_log = new QAction(MainWindow);
        actionVideo_log->setObjectName(QStringLiteral("actionVideo_log"));
        actionInstance_log = new QAction(MainWindow);
        actionInstance_log->setObjectName(QStringLiteral("actionInstance_log"));
        actionDynamic = new QAction(MainWindow);
        actionDynamic->setObjectName(QStringLiteral("actionDynamic"));
        actionFixed = new QAction(MainWindow);
        actionFixed->setObjectName(QStringLiteral("actionFixed"));
        actionShow_Faces = new QAction(MainWindow);
        actionShow_Faces->setObjectName(QStringLiteral("actionShow_Faces"));
        actionAdd_face = new QAction(MainWindow);
        actionAdd_face->setObjectName(QStringLiteral("actionAdd_face"));
        actionTracking = new QAction(MainWindow);
        actionTracking->setObjectName(QStringLiteral("actionTracking"));
        actionAbout_2 = new QAction(MainWindow);
        actionAbout_2->setObjectName(QStringLiteral("actionAbout_2"));
        actionDatabase_Configuration = new QAction(MainWindow);
        actionDatabase_Configuration->setObjectName(QStringLiteral("actionDatabase_Configuration"));
        actionSearch_by_date_and_time = new QAction(MainWindow);
        actionSearch_by_date_and_time->setObjectName(QStringLiteral("actionSearch_by_date_and_time"));
        actionStudent_Attendece = new QAction(MainWindow);
        actionStudent_Attendece->setObjectName(QStringLiteral("actionStudent_Attendece"));
        actionEmployee_Attendence = new QAction(MainWindow);
        actionEmployee_Attendence->setObjectName(QStringLiteral("actionEmployee_Attendence"));
        actionTotal_Present_Time_For_Each_Employe = new QAction(MainWindow);
        actionTotal_Present_Time_For_Each_Employe->setObjectName(QStringLiteral("actionTotal_Present_Time_For_Each_Employe"));
        actionSearch_By_Given_Image = new QAction(MainWindow);
        actionSearch_By_Given_Image->setObjectName(QStringLiteral("actionSearch_By_Given_Image"));
        actionFace_Notification = new QAction(MainWindow);
        actionFace_Notification->setObjectName(QStringLiteral("actionFace_Notification"));
        actionMedia_Player = new QAction(MainWindow);
        actionMedia_Player->setObjectName(QStringLiteral("actionMedia_Player"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 0, 130, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(0, 0, 195, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(0, 0, 162, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(0, 0, 65, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(0, 0, 87, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(0, 0, 127, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(127, 127, 192, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        centralWidget->setPalette(palette);
        verticalLayout = new QVBoxLayout(centralWidget);
        verticalLayout->setSpacing(0);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        horMenu = new QHBoxLayout();
        horMenu->setSpacing(6);
        horMenu->setObjectName(QStringLiteral("horMenu"));
        scrollArea = new QScrollArea(centralWidget);
        scrollArea->setObjectName(QStringLiteral("scrollArea"));
        QPalette palette1;
        QBrush brush9(QColor(255, 255, 255, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        QBrush brush10(QColor(71, 71, 71, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush10);
        QBrush brush11(QColor(106, 106, 106, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush11);
        QBrush brush12(QColor(88, 88, 88, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush12);
        QBrush brush13(QColor(35, 35, 35, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush13);
        QBrush brush14(QColor(47, 47, 47, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush14);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush9);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush9);
        QBrush brush15(QColor(40, 40, 40, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush15);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush10);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush13);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush11);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush14);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush15);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush11);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush14);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        scrollArea->setPalette(palette1);
        scrollArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QStringLiteral("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 1372, 670));
        seachLayoutWidget = new QWidget(scrollAreaWidgetContents);
        seachLayoutWidget->setObjectName(QStringLiteral("seachLayoutWidget"));
        seachLayoutWidget->setGeometry(QRect(0, 0, 1376, 64));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Minimum);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(seachLayoutWidget->sizePolicy().hasHeightForWidth());
        seachLayoutWidget->setSizePolicy(sizePolicy);
        seachLayoutWidget->setMinimumSize(QSize(0, 60));
        seachLayoutWidget->setMaximumSize(QSize(16777215, 100));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        QBrush brush16(QColor(0, 47, 91, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush16);
        QBrush brush17(QColor(0, 0, 191, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush17);
        QBrush brush18(QColor(0, 0, 159, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush18);
        QBrush brush19(QColor(0, 0, 63, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush19);
        QBrush brush20(QColor(0, 0, 84, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush20);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush9);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush9);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush19);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush17);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush18);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush19);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush20);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush16);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush19);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush19);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush17);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush18);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush19);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush19);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush19);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        seachLayoutWidget->setPalette(palette2);
        seachLayoutWidget->setStyleSheet(QStringLiteral("background-color: rgb(0, 47, 91);"));
        horizontalLayout = new QHBoxLayout(seachLayoutWidget);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer);

        startButton = new QPushButton(seachLayoutWidget);
        startButton->setObjectName(QStringLiteral("startButton"));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush21(QColor(73, 168, 53, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush21);
        QBrush brush22(QColor(170, 255, 127, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush22);
        QBrush brush23(QColor(127, 255, 63, 255));
        brush23.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush23);
        QBrush brush24(QColor(42, 127, 0, 255));
        brush24.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush24);
        QBrush brush25(QColor(56, 170, 0, 255));
        brush25.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush25);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush9);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush21);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush21);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush22);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush21);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush22);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush23);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush24);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush25);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush21);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush21);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush22);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush21);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush22);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush23);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush25);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush24);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush21);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush21);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush26(QColor(85, 255, 0, 255));
        brush26.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush26);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        startButton->setPalette(palette3);
        QFont font;
        font.setFamily(QStringLiteral("Tibetan Machine Uni"));
        font.setPointSize(12);
        startButton->setFont(font);
        startButton->setStyleSheet(QStringLiteral("background-color: rgb(73, 168, 53);"));

        horizontalLayout->addWidget(startButton);

        horizontalSpacer_3 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_3);

        iconWC = new QLabel(seachLayoutWidget);
        iconWC->setObjectName(QStringLiteral("iconWC"));
        iconWC->setMinimumSize(QSize(85, 25));

        horizontalLayout->addWidget(iconWC);

        horizontalSpacer_4 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_4);

        tileButton = new QPushButton(seachLayoutWidget);
        tileButton->setObjectName(QStringLiteral("tileButton"));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush16);
        QBrush brush27(QColor(255, 147, 147, 255));
        brush27.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush27);
        QBrush brush28(QColor(247, 94, 94, 255));
        brush28.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush28);
        QBrush brush29(QColor(119, 20, 20, 255));
        brush29.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush29);
        QBrush brush30(QColor(159, 27, 27, 255));
        brush30.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush30);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush9);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush31(QColor(247, 148, 148, 255));
        brush31.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush31);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush27);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush28);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush29);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush30);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush16);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush31);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush29);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush27);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush28);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush29);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush30);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush29);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush9);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush29);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush32(QColor(239, 41, 41, 255));
        brush32.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush32);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        tileButton->setPalette(palette4);
        QFont font1;
        font1.setBold(false);
        font1.setWeight(50);
        tileButton->setFont(font1);
        tileButton->setToolTipDuration(10);

        horizontalLayout->addWidget(tileButton);

        horizontalSpacer_6 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_6);

        faceLineEdit = new QLineEdit(seachLayoutWidget);
        faceLineEdit->setObjectName(QStringLiteral("faceLineEdit"));
        QSizePolicy sizePolicy1(QSizePolicy::Maximum, QSizePolicy::Maximum);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(faceLineEdit->sizePolicy().hasHeightForWidth());
        faceLineEdit->setSizePolicy(sizePolicy1);
        faceLineEdit->setMinimumSize(QSize(150, 25));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush9);
        QBrush brush33(QColor(128, 255, 0, 255));
        brush33.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush33);
        QBrush brush34(QColor(106, 212, 0, 255));
        brush34.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush34);
        QBrush brush35(QColor(42, 85, 0, 255));
        brush35.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush35);
        QBrush brush36(QColor(56, 113, 0, 255));
        brush36.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush36);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush9);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush9);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush37(QColor(170, 212, 127, 255));
        brush37.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush37);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush33);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush34);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush35);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush36);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush37);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush35);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush33);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush34);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush35);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush36);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush35);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush35);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush38(QColor(85, 170, 0, 255));
        brush38.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush38);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        faceLineEdit->setPalette(palette5);
        QFont font2;
        font2.setFamily(QStringLiteral("Ubuntu"));
        font2.setPointSize(11);
        font2.setBold(false);
        font2.setWeight(50);
        faceLineEdit->setFont(font2);
        faceLineEdit->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));

        horizontalLayout->addWidget(faceLineEdit);

        searchFaceButton = new QPushButton(seachLayoutWidget);
        searchFaceButton->setObjectName(QStringLiteral("searchFaceButton"));
        searchFaceButton->setMinimumSize(QSize(25, 25));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush9);
        QBrush brush39(QColor(211, 215, 207, 255));
        brush39.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush39);
        QBrush brush40(QColor(0, 127, 0, 255));
        brush40.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush40);
        QBrush brush41(QColor(0, 106, 0, 255));
        brush41.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush41);
        QBrush brush42(QColor(0, 42, 0, 255));
        brush42.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush42);
        QBrush brush43(QColor(0, 56, 0, 255));
        brush43.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush43);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush9);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush9);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush9);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush39);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush39);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush42);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush39);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush40);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush41);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush42);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush43);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush39);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush39);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush42);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush42);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush39);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush40);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush41);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush42);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush43);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush42);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush42);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush39);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush39);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush44(QColor(0, 85, 0, 255));
        brush44.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush44);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        searchFaceButton->setPalette(palette6);
        QFont font3;
        font3.setFamily(QStringLiteral("URW Bookman L"));
        font3.setPointSize(11);
        font3.setBold(false);
        font3.setItalic(true);
        font3.setWeight(50);
        searchFaceButton->setFont(font3);
        searchFaceButton->setStyleSheet(QStringLiteral("background-color:rgb(211, 215, 207)"));
        QIcon icon;
        icon.addFile(QStringLiteral(":/icons/search.png"), QSize(), QIcon::Normal, QIcon::Off);
        searchFaceButton->setIcon(icon);
        searchFaceButton->setIconSize(QSize(20, 20));

        horizontalLayout->addWidget(searchFaceButton);

        horizontalSpacer_8 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_8);

        horizontalSpacer_5 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_5);

        LPRlineEdit = new QLineEdit(seachLayoutWidget);
        LPRlineEdit->setObjectName(QStringLiteral("LPRlineEdit"));
        sizePolicy1.setHeightForWidth(LPRlineEdit->sizePolicy().hasHeightForWidth());
        LPRlineEdit->setSizePolicy(sizePolicy1);
        LPRlineEdit->setMinimumSize(QSize(150, 25));
        LPRlineEdit->setMaximumSize(QSize(15, 16777215));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush9);
        QBrush brush45(QColor(255, 127, 127, 255));
        brush45.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush45);
        QBrush brush46(QColor(255, 63, 63, 255));
        brush46.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush46);
        QBrush brush47(QColor(127, 0, 0, 255));
        brush47.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush47);
        QBrush brush48(QColor(170, 0, 0, 255));
        brush48.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush48);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush9);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush45);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush45);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush46);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush47);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush48);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush45);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush47);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush45);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush46);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush47);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush48);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush47);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush47);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush49(QColor(255, 0, 0, 255));
        brush49.setStyle(Qt::SolidPattern);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush49);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        LPRlineEdit->setPalette(palette7);
        LPRlineEdit->setStyleSheet(QStringLiteral("background-color: rgb(255, 255, 255);"));

        horizontalLayout->addWidget(LPRlineEdit);

        searchLPRbutton = new QPushButton(seachLayoutWidget);
        searchLPRbutton->setObjectName(QStringLiteral("searchLPRbutton"));
        searchLPRbutton->setMinimumSize(QSize(25, 25));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush39);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush45);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush46);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush47);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush48);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush9);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush39);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush39);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush45);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush39);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush45);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush46);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush47);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush48);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush9);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush39);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush39);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush45);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush47);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush39);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush45);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush46);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush47);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush48);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush47);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush9);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush47);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush39);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush39);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush49);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        searchLPRbutton->setPalette(palette8);
        QFont font4;
        font4.setFamily(QStringLiteral("STIXIntegralsUpD"));
        font4.setPointSize(10);
        font4.setBold(true);
        font4.setWeight(75);
        searchLPRbutton->setFont(font4);
        searchLPRbutton->setStyleSheet(QStringLiteral("background-color:rgb(211, 215, 207)"));
        searchLPRbutton->setIcon(icon);
        searchLPRbutton->setIconSize(QSize(20, 20));

        horizontalLayout->addWidget(searchLPRbutton);

        horizontalSpacer_7 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_7);

        colorCombo = new QComboBox(seachLayoutWidget);
        colorCombo->setObjectName(QStringLiteral("colorCombo"));
        colorCombo->setMinimumSize(QSize(150, 0));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush39);
        QBrush brush50(QColor(127, 255, 255, 255));
        brush50.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush50);
        QBrush brush51(QColor(63, 255, 255, 255));
        brush51.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush51);
        QBrush brush52(QColor(0, 127, 127, 255));
        brush52.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush52);
        QBrush brush53(QColor(0, 170, 170, 255));
        brush53.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush53);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush54(QColor(238, 238, 236, 255));
        brush54.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush54);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush39);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush39);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush54);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush50);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush39);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush50);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush51);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush52);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush53);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush54);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush39);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush39);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush54);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush50);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush52);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush39);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush50);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush51);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush52);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush53);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush52);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush54);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush52);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush39);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush39);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush54);
        QBrush brush55(QColor(0, 255, 255, 255));
        brush55.setStyle(Qt::SolidPattern);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush55);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        colorCombo->setPalette(palette9);
        QFont font5;
        font5.setPointSize(11);
        colorCombo->setFont(font5);
        colorCombo->setStyleSheet(QStringLiteral("background-color:rgb(211, 215, 207)"));

        horizontalLayout->addWidget(colorCombo);

        objectCombo = new QComboBox(seachLayoutWidget);
        objectCombo->setObjectName(QStringLiteral("objectCombo"));
        objectCombo->setMinimumSize(QSize(150, 0));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush39);
        QBrush brush56(QColor(213, 255, 223, 255));
        brush56.setStyle(Qt::SolidPattern);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush56);
        QBrush brush57(QColor(149, 255, 175, 255));
        brush57.setStyle(Qt::SolidPattern);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush57);
        QBrush brush58(QColor(42, 127, 63, 255));
        brush58.setStyle(Qt::SolidPattern);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush58);
        QBrush brush59(QColor(56, 170, 84, 255));
        brush59.setStyle(Qt::SolidPattern);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush59);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush9);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush39);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush39);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush60(QColor(170, 255, 191, 255));
        brush60.setStyle(Qt::SolidPattern);
        palette10.setBrush(QPalette::Active, QPalette::AlternateBase, brush60);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush39);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush56);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush57);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush58);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush59);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush9);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush39);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush39);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush60);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush58);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush39);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush56);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush57);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush58);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush59);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush58);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush9);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush58);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush39);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush39);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush61(QColor(85, 255, 127, 255));
        brush61.setStyle(Qt::SolidPattern);
        palette10.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush61);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        objectCombo->setPalette(palette10);
        objectCombo->setFont(font5);
        objectCombo->setStyleSheet(QStringLiteral("background-color:rgb(211, 215, 207)"));

        horizontalLayout->addWidget(objectCombo);

        searchObjectButton = new QPushButton(seachLayoutWidget);
        searchObjectButton->setObjectName(QStringLiteral("searchObjectButton"));
        searchObjectButton->setMinimumSize(QSize(150, 0));
        searchObjectButton->setMaximumSize(QSize(100, 16777215));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush39);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush56);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush57);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush58);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush59);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush9);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush39);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush39);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush60);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush39);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush56);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush57);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush58);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush59);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush9);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush39);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush39);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush60);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush58);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush39);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush56);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush57);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush58);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush59);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush58);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush9);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush58);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush39);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush39);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush61);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        searchObjectButton->setPalette(palette11);
        QFont font6;
        font6.setFamily(QStringLiteral("Ubuntu"));
        font6.setPointSize(11);
        font6.setBold(false);
        font6.setItalic(false);
        font6.setWeight(50);
        searchObjectButton->setFont(font6);
        searchObjectButton->setStyleSheet(QStringLiteral("background-color:rgb(211, 215, 207)"));

        horizontalLayout->addWidget(searchObjectButton);

        horizontalSpacer_10 = new QSpacerItem(20, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_10);

        pushButton = new QPushButton(seachLayoutWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        QSizePolicy sizePolicy2(QSizePolicy::Minimum, QSizePolicy::Fixed);
        sizePolicy2.setHorizontalStretch(50);
        sizePolicy2.setVerticalStretch(20);
        sizePolicy2.setHeightForWidth(pushButton->sizePolicy().hasHeightForWidth());
        pushButton->setSizePolicy(sizePolicy2);
        QFont font7;
        font7.setItalic(true);
        pushButton->setFont(font7);
        pushButton->setStyleSheet(QStringLiteral("background-color:rgb(186, 189, 182);"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/icons/sigmindLogo.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton->setIcon(icon1);
        pushButton->setIconSize(QSize(40, 40));

        horizontalLayout->addWidget(pushButton);

        horizontalSpacer_11 = new QSpacerItem(20, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_11);

        horizontalSpacer_9 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_9);

        horizontalSpacer_2 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_2);

        scrollArea->setWidget(scrollAreaWidgetContents);

        horMenu->addWidget(scrollArea);


        verticalLayout->addLayout(horMenu);

        feedLayout = new QGridLayout();
        feedLayout->setSpacing(0);
        feedLayout->setObjectName(QStringLiteral("feedLayout"));
        feedLayout->setSizeConstraint(QLayout::SetFixedSize);

        verticalLayout->addLayout(feedLayout);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1376, 22));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush54);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush54);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush54);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipText, brush54);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush54);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush54);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush54);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush16);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush54);
        QBrush brush62(QColor(190, 190, 190, 255));
        brush62.setStyle(Qt::SolidPattern);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush62);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush62);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush62);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush54);
        menuBar->setPalette(palette12);
        menuBar->setStyleSheet(QStringLiteral("background-color: rgb(0,47,91);"));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush54);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush54);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush54);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipText, brush54);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush54);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush54);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush54);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush16);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush54);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush62);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush62);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush62);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush54);
        menuFile->setPalette(palette13);
        menuFile->setFont(font1);
        menuFile->setContextMenuPolicy(Qt::DefaultContextMenu);
        menuFile->setStyleSheet(QStringLiteral(""));
        menuTools = new QMenu(menuBar);
        menuTools->setObjectName(QStringLiteral("menuTools"));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush54);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush54);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush54);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipText, brush54);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush54);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush54);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush54);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush16);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush54);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush62);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush62);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush62);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush54);
        menuTools->setPalette(palette14);
        menuTools->setFont(font1);
        menuAnalyze = new QMenu(menuBar);
        menuAnalyze->setObjectName(QStringLiteral("menuAnalyze"));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush54);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush54);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush54);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipText, brush54);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush54);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush54);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush54);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush16);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush54);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush62);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush62);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush62);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush54);
        menuAnalyze->setPalette(palette15);
        menuLog = new QMenu(menuBar);
        menuLog->setObjectName(QStringLiteral("menuLog"));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush54);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush54);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush54);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipText, brush54);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush54);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush54);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush54);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush16);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush54);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush62);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush62);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush62);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush54);
        menuLog->setPalette(palette16);
        menuView = new QMenu(menuBar);
        menuView->setObjectName(QStringLiteral("menuView"));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush54);
        palette17.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush54);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush54);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette17.setBrush(QPalette::Active, QPalette::ToolTipText, brush54);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush54);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush54);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush54);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush16);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette17.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush54);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush62);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush62);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush62);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette17.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush54);
        menuView->setPalette(palette17);
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QStringLiteral("menuHelp"));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush54);
        palette18.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush54);
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush54);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette18.setBrush(QPalette::Active, QPalette::ToolTipText, brush54);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush54);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush54);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush54);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush16);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette18.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush54);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush62);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush62);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush62);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette18.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush54);
        menuHelp->setPalette(palette18);
        menuDatabase = new QMenu(menuBar);
        menuDatabase->setObjectName(QStringLiteral("menuDatabase"));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush54);
        palette19.setBrush(QPalette::Active, QPalette::Button, brush16);
        palette19.setBrush(QPalette::Active, QPalette::Text, brush54);
        palette19.setBrush(QPalette::Active, QPalette::ButtonText, brush54);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush16);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette19.setBrush(QPalette::Active, QPalette::ToolTipText, brush54);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush54);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette19.setBrush(QPalette::Inactive, QPalette::Text, brush54);
        palette19.setBrush(QPalette::Inactive, QPalette::ButtonText, brush54);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush16);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette19.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush54);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush62);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette19.setBrush(QPalette::Disabled, QPalette::Text, brush62);
        palette19.setBrush(QPalette::Disabled, QPalette::ButtonText, brush62);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette19.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush54);
        menuDatabase->setPalette(palette19);
        menuNotification = new QMenu(menuBar);
        menuNotification->setObjectName(QStringLiteral("menuNotification"));
        menuPlayback = new QMenu(menuBar);
        menuPlayback->setObjectName(QStringLiteral("menuPlayback"));
        MainWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuTools->menuAction());
        menuBar->addAction(menuAnalyze->menuAction());
        menuBar->addAction(menuLog->menuAction());
        menuBar->addAction(menuView->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuBar->addAction(menuDatabase->menuAction());
        menuBar->addAction(menuNotification->menuAction());
        menuBar->addAction(menuPlayback->menuAction());
        menuFile->addAction(actionAdd_Camera);
        menuFile->addAction(actionRemove_Camera);
        menuFile->addAction(actionExport);
        menuFile->addAction(actionShow_Faces);
        menuFile->addAction(actionAdd_face);
        menuTools->addAction(actionSettings);
        menuTools->addAction(actionAdvanced_Search);
        menuTools->addAction(actionRTSS);
        menuTools->addAction(actionRTVS);
        menuTools->addAction(actionTracking);
        menuAnalyze->addAction(actionSuper_Resolution);
        menuAnalyze->addAction(actionFootage_analysis);
        menuAnalyze->addAction(actionStatistics);
        menuLog->addAction(actionVideo_log);
        menuLog->addAction(actionInstance_log);
        menuView->addAction(actionDynamic);
        menuView->addAction(actionFixed);
        menuHelp->addAction(actionAbout_2);
        menuDatabase->addAction(actionDatabase_Configuration);
        menuDatabase->addAction(actionSearch_by_date_and_time);
        menuDatabase->addAction(actionStudent_Attendece);
        menuDatabase->addAction(actionEmployee_Attendence);
        menuDatabase->addSeparator();
        menuDatabase->addAction(actionTotal_Present_Time_For_Each_Employe);
        menuDatabase->addAction(actionSearch_By_Given_Image);
        menuNotification->addAction(actionFace_Notification);
        menuPlayback->addAction(actionMedia_Player);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "WATCHCAM", Q_NULLPTR));
        actionAdd_Camera->setText(QApplication::translate("MainWindow", "Add Camera", Q_NULLPTR));
#ifndef QT_NO_SHORTCUT
        actionAdd_Camera->setShortcut(QApplication::translate("MainWindow", "Ctrl+D", Q_NULLPTR));
#endif // QT_NO_SHORTCUT
        actionRemove_Camera->setText(QApplication::translate("MainWindow", "Remove Camera", Q_NULLPTR));
        actionExport->setText(QApplication::translate("MainWindow", "Export", Q_NULLPTR));
        actionSettings->setText(QApplication::translate("MainWindow", "Settings", Q_NULLPTR));
#ifndef QT_NO_SHORTCUT
        actionSettings->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+S", Q_NULLPTR));
#endif // QT_NO_SHORTCUT
        actionAdvanced_Search->setText(QApplication::translate("MainWindow", "Advanced Search", Q_NULLPTR));
        actionRTSS->setText(QApplication::translate("MainWindow", "RTSS", Q_NULLPTR));
        actionRTVS->setText(QApplication::translate("MainWindow", "RTVS", Q_NULLPTR));
        actionSuper_Resolution->setText(QApplication::translate("MainWindow", "Super Resolution", Q_NULLPTR));
        actionFootage_analysis->setText(QApplication::translate("MainWindow", "Footage analysis", Q_NULLPTR));
#ifndef QT_NO_SHORTCUT
        actionFootage_analysis->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+F", Q_NULLPTR));
#endif // QT_NO_SHORTCUT
        actionStatistics->setText(QApplication::translate("MainWindow", "Statistics", Q_NULLPTR));
        actionVideo_log->setText(QApplication::translate("MainWindow", "Video log", Q_NULLPTR));
        actionInstance_log->setText(QApplication::translate("MainWindow", "Instance log", Q_NULLPTR));
        actionDynamic->setText(QApplication::translate("MainWindow", "Dynamic", Q_NULLPTR));
        actionFixed->setText(QApplication::translate("MainWindow", "Fixed", Q_NULLPTR));
        actionShow_Faces->setText(QApplication::translate("MainWindow", "Show Faces", Q_NULLPTR));
#ifndef QT_NO_SHORTCUT
        actionShow_Faces->setShortcut(QApplication::translate("MainWindow", "Ctrl+F", Q_NULLPTR));
#endif // QT_NO_SHORTCUT
        actionAdd_face->setText(QApplication::translate("MainWindow", "Add face", Q_NULLPTR));
#ifndef QT_NO_SHORTCUT
        actionAdd_face->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+F", Q_NULLPTR));
#endif // QT_NO_SHORTCUT
        actionTracking->setText(QApplication::translate("MainWindow", "Tracking", Q_NULLPTR));
#ifndef QT_NO_SHORTCUT
        actionTracking->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+T", Q_NULLPTR));
#endif // QT_NO_SHORTCUT
        actionAbout_2->setText(QApplication::translate("MainWindow", "About", Q_NULLPTR));
        actionDatabase_Configuration->setText(QApplication::translate("MainWindow", "Database Configuration", Q_NULLPTR));
        actionSearch_by_date_and_time->setText(QApplication::translate("MainWindow", "Search By Date and Time", Q_NULLPTR));
        actionStudent_Attendece->setText(QApplication::translate("MainWindow", "Student Attendece", Q_NULLPTR));
        actionEmployee_Attendence->setText(QApplication::translate("MainWindow", "Employee Attendence", Q_NULLPTR));
        actionTotal_Present_Time_For_Each_Employe->setText(QApplication::translate("MainWindow", "Total_Present_Time_For_Each_Employe", Q_NULLPTR));
        actionSearch_By_Given_Image->setText(QApplication::translate("MainWindow", "Search By Given Image", Q_NULLPTR));
        actionFace_Notification->setText(QApplication::translate("MainWindow", "Face Notification", Q_NULLPTR));
        actionMedia_Player->setText(QApplication::translate("MainWindow", "Media Player", Q_NULLPTR));
        startButton->setText(QApplication::translate("MainWindow", "Settings", Q_NULLPTR));
        iconWC->setText(QApplication::translate("MainWindow", "TextLabel", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        tileButton->setToolTip(QApplication::translate("MainWindow", "show faces here", Q_NULLPTR));
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_STATUSTIP
        tileButton->setStatusTip(QString());
#endif // QT_NO_STATUSTIP
        tileButton->setText(QApplication::translate("MainWindow", "Face Log", Q_NULLPTR));
        faceLineEdit->setPlaceholderText(QApplication::translate("MainWindow", "Search Face", Q_NULLPTR));
        searchFaceButton->setText(QString());
        LPRlineEdit->setText(QString());
        LPRlineEdit->setPlaceholderText(QApplication::translate("MainWindow", "Search License Plate", Q_NULLPTR));
        searchLPRbutton->setText(QString());
        colorCombo->clear();
        colorCombo->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Filter by Color", Q_NULLPTR)
        );
        searchObjectButton->setText(QApplication::translate("MainWindow", "Search Object", Q_NULLPTR));
        pushButton->setText(QApplication::translate("MainWindow", "Powered by Sigmind", Q_NULLPTR));
        menuFile->setTitle(QApplication::translate("MainWindow", "File", Q_NULLPTR));
        menuTools->setTitle(QApplication::translate("MainWindow", "Tools", Q_NULLPTR));
        menuAnalyze->setTitle(QApplication::translate("MainWindow", "Analyze", Q_NULLPTR));
        menuLog->setTitle(QApplication::translate("MainWindow", "Log", Q_NULLPTR));
        menuView->setTitle(QApplication::translate("MainWindow", "View", Q_NULLPTR));
        menuHelp->setTitle(QApplication::translate("MainWindow", "Help", Q_NULLPTR));
        menuDatabase->setTitle(QApplication::translate("MainWindow", "Database", Q_NULLPTR));
        menuNotification->setTitle(QApplication::translate("MainWindow", "Notification", Q_NULLPTR));
        menuPlayback->setTitle(QApplication::translate("MainWindow", "Playback", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
